name: MessageHandler
main: net.messagehandler.MessageHandler
version: 1.0.0 BETA
author: Raymart
api-version: 1.16
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  messagehandler:
    description: Main command
    permission: messagehandler.help
  warn:
    description: warn a player
    permission: messagehandler.warn
  afk:
    description: afk
    permission: messagehandler.afk
  help:
    description: custom help
    permission: messagehandler.help
  motd:
    description: custom motd
    permission: messagehandler.motd
  rules:
    description: server rules
    permission: messagehandler.rules
  vanish:
    description: vanish
    permission: messagehandler.vanish
  broadcast:
    description: broadcast message
    permission: messagehandler.broadcast
  nickname:
    description: change nickname
    permission: messagehandler.nickanme
  clearchat:
    description: clears chat
    permission: messagehandler.clearchat
  realname:
    description: real name of target
    permission: messagehandler.realname
  chatspy:
    description: spy chats
    permission: messagehandler.chatspy
  commandspy:
    description: spy commands
    permission: messagehandler.commandspy
  whisper:
    description: send message to player
    permission: messagehandler.whisper
  reply:
    description: reply to a player
    permission: messagehandler.reply
  ignore:
    description: ignores a player
    permission: messagehandler.ignore
  ignoreall:
    description: ignore all player
    permission: messagehandler.ignoreall
  sendtitle:
    description: send title to a player
    permission: messagehandler.sendtitle

permissions:
  messagehandler.admin:
    description: allow to use all commands
    default: op
    children:
      messagehandler.broadcast: true
      messagehandler.clear: true
      messagehandler.clear.all: true
      messagehandler.clear.other: true
      messagehandler.help: true
      messagehandler.filter: true
      messagehandler.groupchat: true
      messagehandler.groupchat.help: true
      messagehandler.groupchat.create: true
      messagehandler.groupchat.join: true
      messagehandler.groupchat.leave: true
      messagehandler.groupchat.disband: true
      messagehandler.groupchat.members: true
      messagehandler.groupchat.list: true
      messagehandler.groupchat.nickname: true
      messagehandler.list: true
      messagehandler.nickname: true
      messagehandler.reload: true
      messagehandler.chat.color: true
      messagehandler.chat.effect: true

  messagehandler.clear.*:
    description: allow to use all clear commands
    default: op
    children:
      messagehandler.clear: true
      messagehandler.clear.all: true
      messagehandler.clear.other: true

  messagehandler.groupchat.*:
    description: allow to use all groupchat commands
    default: op
    children:
      messagehandler.groupchat: true
      messagehandler.groupchat.help: true
      messagehandler.groupchat.create: true
      messagehandler.groupchat.join: true
      messagehandler.groupchat.leave: true
      messagehandler.groupchat.disband: true
      messagehandler.groupchat.members: true
      messagehandler.groupchat.list: true
      messagehandler.groupchat.nickname: true