name: MessageHandler
main: net.messagehandler.MessageHandler
version: 1.0.0 BETA
author: Raymart
api-version: 1.16
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  messagehandler:
    description: Main command
    permission: messagehandler.help
    aliases: [ml]
  bannedwords:
    description: Check all of the banned words
    permission: messagehandler.gui.bannedwords
    aliases: [words, bwords, bw]
  chat:
    description: Toggle spam with your chat box
    permission: messagehandler.gui.chat
    aliases: [preference, pref]
  groupchat:
    description: Setup groupchat or chat channels
    permission: messagehandler.gui.groupchat
    aliases: [gc, groups]
  email:
    description: To send an email
    permission: messagehandler.gui.email
    aliases: [mail]
  ticket:
    description: To report unwanted things
    permission: messagehandler.gui.ticket
    aliases: [t]
  online:
    description: Show all players online
    permission: messagehandler.gui.online
    aliases: [ol]
  staffs:
    description: Show all admins
    permission: messagehandler.gui.staffs
    aliases: [staff]
  warn:
    description: warn a player
    permission: messagehandler.warn
  afk:
    description: afk
    permission: messagehandler.afk
  help:
    description: custom help
    permission: messagehandler.help
  motd:
    description: custom motd
    permission: messagehandler.motd
  rules:
    description: server rules
    permission: messagehandler.rules
  vanish:
    description: vanish
    permission: messagehandler.vanish
    aliases: [v]
  broadcast:
    description: broadcast message
    permission: messagehandler.broadcast
    aliases: [bcast, b]
  nickname:
    description: change nickname
    permission: messagehandler.nickanme
    aliases: [nick]
  clearchat:
    description: clears chat
    permission: messagehandler.clearchat
    aliases: [cc]
  realname:
    description: real name of target
    permission: messagehandler.realname
    aliases: [who, rname]
  chatspy:
    description: spy chats
    permission: messagehandler.chatspy
  commandspy:
    description: spy commands
    permission: messagehandler.commandspy
  whisper:
    description: send message to player
    permission: messagehandler.whisper
    aliases: [msg, m, w]
  reply:
    description: reply to a player
    permission: messagehandler.reply
    aliases: [r]
  ignore:
    description: ignores a player
    permission: messagehandler.ignore
  ignoreall:
    description: ignore all player
    permission: messagehandler.ignoreall
  sendtitle:
    description: send title to a player
    permission: messagehandler.sendtitle
    aliases: [title]
  customization:
    description: customize everything
    aliases: [custom, customize]

permissions:
  messagehandler.admin:
    description: allow to use all commands
    default: op
    children:
      messagehandler.afk: true
      messagehandler.broadcast: true
      messagehandler.clear.*: true
      messagehandler.spy: true
      messagehandler.command.*: true
      messagehandler.help: true
      messagehandler.ignore: true
      messagehandler.ignoreall: true
      messagehandler.motd: true
      messagehandler.nick: true
      messagehandler.realname: true
      messagehandler.rules: true
      messagehandler.sendtitle: true
      messagehandler.vanish: true
      messagehandler.warn: true
      messagehandler.message: true
      messagehandler.gui.*: true

  messagehandler.command.*:
    description: allow to use all /messagehandler commands
    default: op
    children:
       messagehandler.command: true
       messagehandler.help: true
       messagehandler.reload: true

  messagehandler.gui.*:
     description: allow to use all gui commands
     default: op
     children:
        messagehandler.bannedwords: true
        messagehandler.chat: true
        messagehandler.customization: true
        messagehandler.email: true
        messagehandler.groupchat: true
        messagehandler.online: true
        messagehandler.staffs: true
        messagehandler.customize.*: true
        messagehandler.groups.*: true
        messagehandler.tickets.*: true

  messagehandler.tickets.*:
     description: ticket events
     default: op
     children:
       messagehandler.ticket: true
       messagehandler.ticketadmin: true
       messagehandler.ticketplayer: true

  messagehandler.groups.*:
     description: groupchat events
     default: op
     children:
       messagehandler.groups.groups: true
       messagehandler.groups.personal: true
       messagehandler.groups.create: true

  messagehandler.customize.*:
     description: allow to use all customize events
     default: op
     children:
       messagehandler.customize.join: true
       messagehandler.customize.quit: true
       messagehandler.customize.nametag: true
       messagehandler.customize.chat: true

  messagehandler.spy:
     description: spy chat or command
     default: op
     children:
        messagehandler.commandspy: true
        messagehandler.chatspy: true

  messagehandler.message:
      description: allow to use all commands
      default: op
      children:
         messagehandler.whisper: true
         messagehandler.reply: true

  messagehandler.clear.*:
    description: allow to use all clear commands
    default: op
    children:
      messagehandler.clear: true
      messagehandler.clear.all: true
      messagehandler.clear.other: true

  # having filtermsg permission will let you swear
  # having filterad permission will let you advertise
  messagehandler.anvil.*:
    description: allow to use all anvil listeners
        default: op
        children:
           messagehandler.anvil.color: true
           messagehandler.anvil.format: true
           messagehandler.anvil.filterad: true
           messagehandler.anvil.filtermsg: true

  messagehandler.sign.*:
      description: allow to use all anvil listeners
          default: op
          children:
             messagehandler.sign.color: true
             messagehandler.sign.format: true
             messagehandler.sign.filterad: true
             messagehandler.sign.filtermsg: true

  messagehandler.book.*:
      description: allow to use all anvil listeners
          default: op
          children:
             messagehandler.book.color: true
             messagehandler.book.format: true
             messagehandler.book.filterad: true
             messagehandler.book.filtermsg: true


  messagehandler.chat.*:
     description: allows you to skip filtering messages
        default: op
        children:
           messagehandler.antiad.bypass: true
           messagehandler.antiunicode.bypass: true
           messagehandler.anticaps.bypass: true
           messagehandler.antiswear.bypass: true
           messagehandler.chat.global: true
           messagehandler.commandblocker.bypass: true
           messagehandler.ping: true
           messagehandler.pingall: true
           messagehandler.chatcooldown.bypass: true
